# Documentation: https://github.com/JuliaCI/Appveyor.jl
environment:
  matrix:
  - julia_version: 1
  # - julia_version: nightly
platform:
  - x86
  - x64
# matrix:
#   allow_failures:
#     - julia_version: nightly
branches:
  only:
    - main
    - /release-.*/
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
install:
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
        "C:\projects\julia-binary.exe")
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia
build_script:
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"Optini\"); Pkg.build(\"Optini\")"
test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"Optini\")"