# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
branches:
  only:
    - main
os:
  - linux
  - osx
julia:
  - 1
#   - nightly
# matrix:
#   allow_failures:
#     - julia: nightly
#   fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Optini"); Pkg.test("Optini"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Optini")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Optini")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'